name: Feature request
description: Suggest a new algorithm, enhancement to an existing algorithm, etc.
labels: ['New Feature', 'enhancement', 'Needs Triage']

body:
- type: markdown
  attributes:
    value: >
      #### If you want to propose a new algorithm/feauture,  Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
- type: textarea
  attributes:
    label: Describe the workflow you want to enable
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe your proposed solution or features you have considered.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
