name: CI Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    # Steps for the build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Run unit tests with nose
        run: nosetests
     
      # Uncomment the following 2 lines during hands-on lab
      
      # - name: Upload code coverage
      #   uses: codecov/codecov-action@v2
      #   with:
      #     version: "v0.1.13"      
  
